/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static java.awt.EventQueue.invokeLater;
import static java.lang.System.exit;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ricar
 */
public class FrmPrincipalA extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipalA() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        jPanel1.setBackground(Color.DARK_GRAY);
        ImageIcon Logo = new ImageIcon(getClass().getResource("/Vista/Imagenes/Logo3.png"));
        Icon fondoLogo = new ImageIcon(Logo.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(fondoLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnTAlimentos = new javax.swing.JButton();
        btnTAlnimales = new javax.swing.JButton();
        btnTlRaciones = new javax.swing.JButton();
        btnTUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnRegistrarAnimal = new javax.swing.JMenuItem();
        btnRegistrarAlimento = new javax.swing.JMenuItem();
        btnRegistrarUsuario = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Principal - Sistema de Formulación de Raciones");

        btnTAlimentos.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnTAlimentos.setText("Tabla de Alimentos");
        btnTAlimentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        btnTAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAlimentosActionPerformed(evt);
            }
        });

        btnTAlnimales.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnTAlnimales.setText("Tabla de Animales");
        btnTAlnimales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        btnTAlnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAlnimalesActionPerformed(evt);
            }
        });

        btnTlRaciones.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnTlRaciones.setText("Análisis de Raciones");
        btnTlRaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        btnTlRaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTlRacionesActionPerformed(evt);
            }
        });

        btnTUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnTUsuarios.setText("Tabla de Usuarios");
        btnTUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        btnTUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Break", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA  DE  FORMULACION  DE  RACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnTAlnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnTlRaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnTUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTAlnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTlRaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnCerrarSesion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(btnCerrarSesion);

        btnSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registrar");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnRegistrarAnimal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarAnimal.setText("Animal");
        btnRegistrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAnimalActionPerformed(evt);
            }
        });
        jMenu2.add(btnRegistrarAnimal);

        btnRegistrarAlimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarAlimento.setText("Alimento");
        btnRegistrarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlimentoActionPerformed(evt);
            }
        });
        jMenu2.add(btnRegistrarAlimento);

        btnRegistrarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrarUsuario.setText("Usuario");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(btnRegistrarUsuario);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAlimentosActionPerformed
        var form = new FrmAlimentos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTAlimentosActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        var form = new RegistrarUsuarios();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        var form = new Login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAnimalActionPerformed
       var form = new RegistrarAnimales();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarAnimalActionPerformed

    private void btnRegistrarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlimentoActionPerformed
        var form = new RegistrarAlimentos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarAlimentoActionPerformed

    private void btnTAlnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAlnimalesActionPerformed
        var form = new FrmAnimales();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTAlnimalesActionPerformed

    private void btnTlRacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTlRacionesActionPerformed
        var form = new FrmRaciones();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTlRacionesActionPerformed

    private void btnTUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTUsuariosActionPerformed
        var form = new FrmUsuarios();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (var info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(FrmPrincipalA.class.getName()).log(SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new FrmPrincipalA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnRegistrarAlimento;
    private javax.swing.JMenuItem btnRegistrarAnimal;
    private javax.swing.JMenuItem btnRegistrarUsuario;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JButton btnTAlimentos;
    private javax.swing.JButton btnTAlnimales;
    private javax.swing.JButton btnTUsuarios;
    private javax.swing.JButton btnTlRaciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
